version: "3.9"
services:
  auth:
    build: auth
    ports:
      - 5000:5000
    volumes:
      - ./db:/data
      - ./auth/app:/app
    environment:
      - FLASK_ENV=development

  proxy:
    image: nginx:1.21
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  job:
    build: job
    ports:
      - 3000:5000
    volumes:
      - ./db:/data     
      - ./job/app:/app
    environment:
      - FLASK_ENV=development



